@startuml

title Class diagram: hyperOptimize

/' Define the class details'/

package view {
    class ProjectView
    class HomeView
    class ModelView
    abstract class LoadDataView
        class LoadTrainingDataView
        class LoadNewDataView
    class OptimizeParamsView
    class EstimatedTimeView
}

package presenter {
    class ProjectPresenter
    class ModelPresenter
    abstract class LoadDataPresenter
    class LoadTrainingDataPresenter
    class LoadNewDataPresenter
    class OptimizeParamsPresenter
    class EstimatedTimePresenter
    class CategorizeDataPresenter
    class HomePresenter{
    + modelPresenter()
    + loadDataPresenter()
    + optimizeParamsPresenter()
    + estimateTimePresenter()
    }
}


package logic {
    class RangeForHyperParamsObj
    class HyperParamsObj
    class ProjectModel
    class HomeModel
    class MachineLearningModel
    abstract class LoadDataModel
        class LoadTrainingDataModel
        class LoadNewDataModel
    class OptimizeParamsModel
    class EstimateTimeModel
}

package persistence {
    class SaverLoader {
        + saveModel(Model)
        + loadModel()
        + saveEstimatedTime()
        + loadEstimatedTime()
    }

}


/' Define relations'/

/' View'/
LoadDataView <|-- LoadTrainingDataView
LoadDataView <|-- LoadNewDataView

/' Presenter'/
LoadDataPresenter <|-- LoadTrainingDataPresenter
LoadDataPresenter <|-- LoadNewDataPresenter

HomeView "1" -- "1" HomePresenter
ProjectView "1" -- "1" ProjectPresenter
ModelView "1" -- "1" ModelPresenter
LoadDataView "1" -- "1" LoadDataPresenter
LoadTrainingDataView "1" -- "1" LoadTrainingDataPresenter
LoadNewDataView "1" -- "1" LoadNewDataPresenter
OptimizeParamsView "1" -- "1" OptimizeParamsPresenter
EstimatedTimeView "1" -- "1" EstimatedTimePresenter

/' Presenter - Model'/
HomePresenter "1" -- "1" HomeModel
ProjectPresenter "1" -- "1" ProjectModel
ModelPresenter "1" -- "1" MachineLearningModel
LoadDataPresenter "1" -- "1" LoadDataModel
LoadTrainingDataPresenter "1" -- "1" LoadTrainingDataModel
LoadNewDataPresenter "1" -- "1" LoadNewDataModel
OptimizeParamsPresenter "1" -- "1" OptimizeParamsModel
EstimatedTimePresenter "1" -- "1" EstimateTimeModel

/' Model'/
LoadDataModel <|-- LoadTrainingDataModel
LoadDataModel <|-- LoadNewDataModel

HomeModel "1" -- "n" ProjectModel
ProjectModel "1" -- "n" MachineLearningModel
MachineLearningModel "1" -- "1" LoadTrainingDataModel
MachineLearningModel "1" -- "1" OptimizeParamsModel
OptimizeParamsModel "1" -- "1" EstimateTimeModel



/' Model - Presenter'/
MachineLearningModel "1" -- "1" SaverLoader
EstimateTimeModel "1" -- "1" SaverLoader

@enduml

