@startuml
allowmixing

title Class diagram: hyperOptimize

/' Define the class details'/



package view {
    package tools {
        class LayoutConstants
        class RangeSlider
        class CreateToolTip
        class ValidationFunctions
    }
    class HomeView
    class LoadDataView
    class MainView
    class ControlFrame
    class ModelView
    class OptimizeModelView
    class ProjectView
}

package logic {
    class EstimateTimeModel
    class HyperParamsObj
    class LoadDataModel
    class MachineLearningModel
    class OptimizeParamsModel
    class RangeForHyperParamsObj
}

package keras{}


package persistence {
    package core {
        class DataBaseConnector
    }

    package dbInteraction {
        class DatabaseProjectModel
        class DataInteractionModel
        class ModelInteractionModel
        class ProjectInteractionModel
    }

    class FileSystemRepository
}

database DB


/' view'/
ControlFrame "1" -- "1" ProjectView
ControlFrame "1" -- "1" HomeView
ControlFrame "1" -- "1" ModelView
ControlFrame "1" -- "1" OptimizeModelView
ControlFrame "1" -- "1" LoadDataView

MainView "1" -- "1" ProjectView
MainView "1" -- "1" HomeView
MainView "1" -- "1" ModelView
MainView "1" -- "1" OptimizeModelView
MainView "1" -- "1" LoadDataView

HomeView "1" -- "1" ProjectInteractionModel

LoadDataView "1" -- "1" DataInteractionModel
LoadDataView "1" -- "1" LoadDataModel
LoadDataView "1" - "1" LayoutConstants
LoadDataView "1" - "1" ValidationFunctions

ModelView "1" -- "1" MachineLearningModel
ModelView "1" - "1" LayoutConstants
ModelView "1" - "1" ValidationFunctions

OptimizeModelView "1" -- "1" DataInteractionModel
OptimizeModelView "1" -- "1" ModelInteractionModel
OptimizeModelView "1" -- "1" MachineLearningModel
OptimizeModelView "1" -- "1" RangeForHyperParamsObj
OptimizeModelView "1" -- "1" OptimizeParamsModel
OptimizeModelView "1" -- "1" LoadDataModel
OptimizeModelView "1" - "1" LayoutConstants
OptimizeModelView "1" - "1" ValidationFunctions

ProjectView "1" -- "1" DatabaseProjectModel
ProjectView "1" -- "1" ProjectInteractionModel
ProjectView "1" -- "1" ModelInteractionModel
ProjectView "1" -- "1" LoadDataModel
ProjectView "1" - "1" LayoutConstants


/' Logic'/
EstimateTimeModel "1" -- "1" FileSystemRepository

LoadDataModel "1" -- "1" FileSystemRepository

MachineLearningModel "1" -- "1" keras
MachineLearningModel "1" - "n" HyperParamsObj

OptimizeParamsModel "1" -- "1" FileSystemRepository
OptimizeParamsModel "1" - "n" MachineLearningModel
OptimizeParamsModel "1" - "1" EstimateTimeModel
OptimizeParamsModel "1" - "1" RangeForHyperParamsObj

RangeForHyperParamsObj "1" - "n" HyperParamsObj

/' Persistence'/
DataBaseConnector "1" -- "1" DB

HyperParamsObj "1" -- "1" DataBaseConnector
MachineLearningModel "1" -- "1" DataBaseConnector
LoadDataModel "1" -- "1" DataBaseConnector
DatabaseProjectModel "1" - "1" DataBaseConnector
DataInteractionModel "1" - "1" DataBaseConnector

LoadDataModel "1" -- "1" DataInteractionModel

DataBaseConnector "1" - "1" ModelInteractionModel
HyperParamsObj "1" -- "1" ModelInteractionModel
MachineLearningModel "1" -- "1" ModelInteractionModel

ProjectInteractionModel "1" - "1" DataBaseConnector
ProjectInteractionModel "1" - "1" DataInteractionModel





@enduml

